<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menus')->insert([
            // Main Courses
            [
                'menu_name' => 'Beef Wellington',
                'menu_price' => '100',
                'menu_type' => 'Dining Room',
                'menu_category' => 'A la carte',
                'menu_desc' => 'Filet mignon, mushroom duxelle, encased in puff pastry. A classic British dish featuring tender beef tenderloin coated with pâté, wrapped in puff pastry, and baked to golden perfection, delivering a delightful combination of textures and flavors.',
                'menu_image' => 'Beef Wellington.png',
            ],
            [
                'menu_name' => 'Aylesbury Ballotine',
                'menu_price' => '45',
                'menu_type' => 'Dining Room',
                'menu_category' => 'A la carte',
                'menu_desc' => 'Aylesbury duck, pickled Kent cherries, hazelnut, onion and spiced pain perdu. A gourmet dish showcasing Aylesbury duck, pickled Kent cherries, hazelnuts, onions, and spiced pain perdu, offering a sophisticated blend of savory, tangy, and nutty flavors.',
                'menu_image' => 'Aylesbury Ballotine.png',
            ],
            [
                'menu_name' => 'Yorkshire Roast Grouse',
                'menu_price' => '40',
                'menu_type' => 'Dining Room',
                'menu_category' => 'A la carte',
                'menu_desc' => 'A roast grouse recipe with game chips, bread sauce and gravy. A traditional British delicacy featuring grouse, a richly flavored game bird, roasted to perfection and served with a delectable combination of Yorkshire pudding, game chips, and a tangy fruit-based sauce, offering a hearty and robust dining experience.',
                'menu_image' => 'Yorkshire Roast Grouse.png',
            ],
            [
                'menu_name' => 'Braised Venison',
                'menu_price' => '30',
                'menu_type' => 'Dining Room',
                'menu_category' => 'A la carte',
                'menu_desc' => 'Braised venison, German black lager, blackberries and juniper berries. A savory dish combining tender braised venison with the robust flavors of German black lager, accompanied by the sweet-tart essence of blackberries and the aromatic touch of juniper berries, resulting in a hearty and nuanced culinary experience.',
                'menu_image' => 'Braised Venison.png',
            ],
            [
                'menu_name' => 'Lemon Sole Fillets with Salsa Verde',
                'menu_price' => '32',
                'menu_type' => 'Dining Room',
                'menu_category' => 'A la carte',
                'menu_desc' => 'Lemon sole fillets, vibrant salsa verde, and zesty green sauce. Delicate lemon sole fillets paired with vibrant salsa verde, a zesty green sauce comprising fresh herbs, capers, garlic, and olive oil, creating a light and refreshing seafood dish with a burst of herbaceous flavors.',
                'menu_image' => 'Lemon Sole Fillets.png',
            ],
            [
                'menu_name' => 'Braised Lamb Pie',
                'menu_price' => '48',
                'menu_type' => 'Dining Room',
                'menu_category' => 'A la carte',
                'menu_desc' => 'Lamb loin, with flaky pastry, and rosemary. A comforting savory pie featuring tender braised lamb enveloped in a flaky pastry crust, offering a rich and hearty dining experience with a perfect balance of meaty and buttery flavors.',
                'menu_image' => 'Braised Lamb Pie.png',
            ],
            [
                'menu_name' => 'Dover Sole meunière',
                'menu_price' => '69',
                'menu_type' => 'Dining Room',
                'menu_category' => 'A la carte',
                'menu_desc' => 'Dover sole fillet, clarified butter, and zesty lemon. A classic French dish showcasing delicate Dover sole cooked in a delectable meunière sauce comprising butter, lemon juice, and parsley, creating a harmonious blend of rich, tangy, and herby flavors.',
                'menu_image' => 'Dover Sole meuniere.png',
            ],
            // Side Dishes
            [
                'menu_name' => 'Artichoke and Wild Berries',
                'menu_price' => '19',
                'menu_type' => 'Dining Room',
                'menu_category' => 'Side Dish',
                'menu_desc' => 'Violet artichoke, blackberry. A delightful mix of artichokes and assorted wild berries for a vibrant salad experience.',
                'menu_image' => 'Artichoke and Wild Berries.png',
            ],
            [
                'menu_name' => 'English Cheese Board',
                'menu_price' => '13',
                'menu_type' => 'Dining Room',
                'menu_category' => 'Side Dish',
                'menu_desc' => 'Cornish brie, Gloucester, Red Leicester, West Country Cheddar. A delightful selection of assorted English cheeses, served with wine and fruits for a flavorful and diverse tasting experience.',
                'menu_image' => 'English Cheese Board.png',
            ],
            [
                'menu_name' => 'Confit Potatoes',
                'menu_price' => '6',
                'menu_type' => 'Dining Room',
                'menu_category' => 'Side Dish',
                'menu_desc' => 'Black garlic, ketchup. A delectable dish featuring tender confit potatoes paired with the rich, savory flavors of black garlic ketchup, offering a satisfying blend of textures and tastes.',
                'menu_image' => 'Confit Potatoes.png',
            ],
            [
                'menu_name' => 'Peppered Swede',
                'menu_price' => '6',
                'menu_type' => 'Dining Room',
                'menu_category' => 'Side Dish',
                'menu_desc' => 'Swede, pepper, and butter. A simple and flavorful dish featuring swede seasoned with a peppery kick, delivering a delightful balance of sweet and spicy flavors.',
                'menu_image' => 'Peppered Swede.png',
            ],
            // Desserts
            [
                'menu_name' => 'Earl Grey Panna Cotta',
                'menu_price' => '6',
                'menu_type' => 'Dining Room',
                'menu_category' => 'Desserts',
                'menu_desc' => 'Milk ice cream, honey biscuit. A silky blend of Italian panna cotta infused with aromatic Earl Grey tea, adorned with honey or berries for a touch of sophistication.',
                'menu_image' => 'Earl Grey Panna Cotta.png',
            ],
            [
                'menu_name' => 'Dark Chocolate and Blackberry',
                'menu_price' => '15',
                'menu_type' => 'Dining Room',
                'menu_category' => 'Desserts',
                'menu_desc' => 'Blackberry marmalade, extra-bitter dark chocolate ganache. A perfect pairing of bitter dark chocolate ganache and tangy blackberry marmalade, offering a harmonious blend of rich and fruity flavors.',
                'menu_image' => 'Dark Chocolate and Blackberry.png',
            ],
            [
                'menu_name' => 'Apple Pie',
                'menu_price' => '15',
                'menu_type' => 'Dining Room',
                'menu_category' => 'Desserts',
                'menu_desc' => 'Apples, with traditional pie. A classic dessert featuring tender, spiced apple slices encased in a flaky pastry crust, delivering a comforting blend of sweet and tart flavors.',
                'menu_image' => 'Apple Pie.png',
            ],
            [
                'menu_name' => 'Lemon and Thyme Sorbet',
                'menu_price' => '15',
                'menu_type' => 'Dining Room',
                'menu_category' => 'Desserts',
                'menu_desc' => 'Sweet honey, zesty lemon, and aromatic thyme. A refreshing fusion of zesty lemon and aromatic thyme, offering a vibrant and herbaceous flavor profile perfect for both savory and sweet culinary creations.',
                'menu_image' => 'Lemon and Thyme Sorbet.png',
            ],
            [
                'menu_name' => 'Platinum Pudding',
                'menu_price' => '15',
                'menu_type' => 'Dining Room',
                'menu_category' => 'Desserts',
                'menu_desc' => 'Lemon curd, Amaretti biscuits and custard. Crafted by Jemma Melvin for Queen Elizabeth II\'s Platinum Jubilee competition in 2022.',
                'menu_image' => 'Platinum Pudding.png',
            ],
            // Island of Mull Scallops
            [
                'menu_name' => 'Island of Mull Scallops',
                'menu_price' => '35',
                'menu_type' => 'Course Experience',
                'menu_category' => 'Package',
                'menu_desc' => 'Hand dived Mull Scallops, succulent apple, celeries. Succulent and flavorsome scallops sourced from the pristine waters of the Isle of Mull, offering a fresh and delectable seafood experience.',
                'menu_image' => 'Island of Mull Scallops.png',
            ],
            // Ballotine of Duck Liver with Damson and Pistachio
            [
                'menu_name' => 'Ballotine of Duck Liver with Damson and Pistachio',
                'menu_price' => '28',
                'menu_type' => 'Course Experience',
                'menu_category' => 'Package',
                'menu_desc' => 'Damson jelly, pistachio yogurt, spiced port jelly, marinated liver. A gourmet dish featuring rich and delicate duck liver wrapped and cooked to perfection, offering a luxurious and flavorful dining experience.',
                'menu_image' => 'Ballotine of Duck Liver with Damson and Pistachio.png',
            ],
            // Heritage Potato Oyster and Crème Crue
            [
                'menu_name' => 'Heritage Potato Oyster and Crème Crue',
                'menu_price' => '15',
                'menu_type' => 'Course Experience',
                'menu_category' => 'Package',
                'menu_desc' => 'Potatoes, oysters, and crème crue. A refined combination of heritage potatoes, oysters, and crème crue for an elegant culinary experience.',
                'menu_image' => 'Heritage Potato Oyster and Crème Crue.png',
            ],
            // Langoustine À la Nage and Bronze Fennel
            [
                'menu_name' => 'Langoustine À la Nage and Bronze Fennel',
                'menu_price' => '38',
                'menu_type' => 'Course Experience',
                'menu_category' => 'Package',
                'menu_desc' => 'Scottish duck, white wine, fennel, leeks. Succulent langoustine in flavorful broth, served with aromatic bronze fennel for a luxurious experience.',
                'menu_image' => 'Langoustine À la Nage and Bronze Fennel.png',
            ],
            // Anjou Pigeon À la Presse
            [
                'menu_name' => 'Anjou Pigeon À la Presse',
                'menu_price' => '40',
                'menu_type' => 'Course Experience',
                'menu_category' => 'Package',
                'menu_desc' => 'Anjou pigeon, pomme soufflée, and baked kohlrabi. An elegant dish featuring Anjou pigeon, pomme soufflée, and baked kohlrabi, delivering a refined and flavorful dining experience.',
                'menu_image' => 'Anjou Pigeon À la Presse.png',
            ],
            // Grill
            // Snacks & Side Dishes
            [
                'menu_name' => 'Beer Battered Onion Rings',
                'menu_price' => '6',
                'menu_type' => 'Grill',
                'menu_category' => 'Snacks & Side Dishes',
                'menu_desc' => 'Crispy and flavorful onion rings coated in a light and airy beer batter, offering a delightful blend of sweet onion and savory beer-infused crunch.',
                'menu_image' => 'Beer Battered Onion Rings.png',
            ],
            [
                'menu_name' => 'Triple Cooked Chips',
                'menu_price' => '6',
                'menu_type' => 'Grill',
                'menu_category' => 'Snacks & Side Dishes',
                'menu_desc' => 'Crispy and fluffy chips with a satisfying crunch, cooked through a meticulous triple-cooking process.',
                'menu_image' => 'Triple Cooked Chips.png',
            ],
            [
                'menu_name' => 'Creamy Mash Potato',
                'menu_price' => '6',
                'menu_type' => 'Grill',
                'menu_category' => 'Snacks & Side Dishes',
                'menu_desc' => 'Smooth and velvety mashed potatoes offering a comforting and indulgent side dish.',
                'menu_image' => 'Creamy Mash Potato.png',
            ],
            [
                'menu_name' => 'Parmesan and Truffle Fries',
                'menu_price' => '6',
                'menu_type' => 'Grill',
                'menu_category' => 'Snacks & Side Dishes',
                'menu_desc' => 'Crispy fries seasoned with aromatic truffle oil and topped with grated Parmesan, providing a delightful combination of earthy, savory, and cheesy flavors.',
                'menu_image' => 'Parmesan and Truffle Fries.png',
            ],
            // Starters & Small Plates
            [
                'menu_name' => 'Angels on Horsebacks',
                'menu_price' => '20',
                'menu_type' => 'Grill',
                'menu_category' => 'Starters & Small Plates',
                'menu_desc' => 'Bacon, oysters, and bread crust. A delectable appetizer featuring oysters wrapped in bacon and grilled to perfection, offering a delightful blend of briny seafood and smoky, savory bacon flavors.',
                'menu_image' => 'Angels on Horsebacks.png',
            ],
            [
                'menu_name' => 'Wild Game Terrine',
                'menu_price' => '21',
                'menu_type' => 'Grill',
                'menu_category' => 'Starters & Small Plates',
                'menu_desc' => 'Bacon, pork, game meat. A rustic and flavorful terrine combining assorted wild game meats with bacon and pork, offering a rich and hearty appetizer or charcuterie option.',
                'menu_image' => 'Wild Game Terrine.png',
            ],
            [
                'menu_name' => 'Aberdeen Angus Steak Tartare',
                'menu_price' => '21',
                'menu_type' => 'Grill',
                'menu_category' => 'Starters & Small Plates',
                'menu_desc' => 'Clarence Court Egg, parmesan crisps. A refined dish featuring finely chopped beef, a Clarence Court egg, and crispy Parmesan for a delightful culinary experience.',
                'menu_image' => 'Aberdeen Angus Steak Tartare.png',
            ],
            [
                'menu_name' => 'Roast Hand Dived Scallops',
                'menu_price' => '20',
                'menu_type' => 'Grill',
                'menu_category' => 'Starters & Small Plates',
                'menu_desc' => 'Celeriac puree, samphire, nduja. A gourmet dish showcasing succulent scallops, creamy celeriac puree, flavorful samphire, and a spicy nduja, offering a delightful balance of textures and tastes.',
                'menu_image' => 'Roast Hand Dived Scallops.png',
            ],
            // Salads
            [
                'menu_name' => 'Goat Cheese Salad',
                'menu_price' => '18',
                'menu_type' => 'Grill',
                'menu_category' => 'Salads',
                'menu_desc' => 'Sourdough Bread, Beetroot and Honey Mustard. A refreshing blend of creamy goat cheese, crispy sourdough, earthy beetroot, and tangy-sweet honey mustard dressing.',
                'menu_image' => 'Goat Cheese Salad.png',
            ],
            [
                'menu_name' => 'Maison Cobb Salad',
                'menu_price' => '16',
                'menu_type' => 'Grill',
                'menu_category' => 'Salads',
                'menu_desc' => "Hen's Egg, Baby Gem, Tomato, Cucumber, Avocado. A refreshing and classic salad ensemble showcasing a delightful mix of fresh ingredients, providing a satisfying blend of textures and flavors.",
                'menu_image' => 'Maison Cobb Salad.png',
            ],
            // Mains
            [
                'menu_name' => 'Maison Fish and Chips',
                'menu_price' => '30',
                'menu_type' => 'Grill',
                'menu_category' => 'Mains',
                'menu_desc' => 'Garden Peas, Triple-Cooked Chips, Tartare Sauce, Curry Sauce. Crispy fish with triple-cooked chips, garden peas, tartare sauce, and optional curry sauce for a classic British meal.',
                'menu_image' => 'Maison Fish and Chips.png',
            ],
            [
                'menu_name' => 'Cheese and Chicken Waffles',
                'menu_price' => '30',
                'menu_type' => 'Grill',
                'menu_category' => 'Mains',
                'menu_desc' => 'Buttermilk-Fried Chicken, Spring Onion, Sriracha. A savory combination of cheesy waffles, crispy fried chicken, and zesty Sriracha for a satisfying meal.',
                'menu_image' => 'Cheese and Chicken Waffles.png',
            ],
            [
                'menu_name' => 'Fillet of Cod',
                'menu_price' => '31',
                'menu_type' => 'Grill',
                'menu_category' => 'Mains',
                'menu_desc' => 'Crushed Baby Potatoes, Barbecued Baby Gem, Miso Sauce. A delicious dish featuring tender cod, crushed potatoes, grilled baby gem, and savory miso sauce for a delightful meal.',
                'menu_image' => 'Fillet of Cod.png',
            ],
            [
                'menu_name' => 'Gnocchi',
                'menu_price' => '26',
                'menu_type' => 'Grill',
                'menu_category' => 'Mains',
                'menu_desc' => 'Peas, prawns, cauliflower. A delicious blend of soft gnocchi, prawns, cauliflower, pesto, and parmesan for a satisfying meal.',
                'menu_image' => 'Gnocchi.png',
            ],
            [
                'menu_name' => 'Roast Crown of Mallard',
                'menu_price' => '33',
                'menu_type' => 'Grill',
                'menu_category' => 'Mains',
                'menu_desc' => 'Honey-glazed mallard, confit leg, turnips, cavolo nero. A gourmet dish featuring succulent mallard with honey glaze, confit leg, turnips, and cavolo nero for a rich and savory meal.',
                'menu_image' => 'Roast Crown of Mallard.png',
            ],
            // Grills
            [
                'menu_name' => 'Maison Burger',
                'menu_price' => '28',
                'menu_type' => 'Grill',
                'menu_category' => 'Grills',
                'menu_desc' => 'Maple-Cured Bacon, Monterey Jack Cheese, Caramelized Onions, Maison Burger Sauce, Fries. A flavorful burger topped with sweet bacon, gooey cheese, and caramelized onions, accompanied by crispy fries for a satisfying meal.',
                'menu_image' => 'Maison Burger.png',
            ],
            [
                'menu_name' => 'Chateaubriand for Two People',
                'menu_price' => '100',
                'menu_type' => 'Grill',
                'menu_category' => 'Grills',
                'menu_desc' => 'Tomato and Mexican tomato salsa. A savory steak dish paired with fresh tomatoes and zesty Mexican salsa, creating a delightful fusion of flavors.',
                'menu_image' => 'Chateaubriand for Two People.png',
            ],
            [
                'menu_name' => "Surf'n'turf",
                'menu_price' => '52',
                'menu_type' => 'Grill',
                'menu_category' => 'Grills',
                'menu_desc' => 'Fillet, 3 prawns. A delectable combination of tender fillet steak and three succulent prawns, delivering a delightful contrast of land and sea flavors in one satisfying dish.',
                'menu_image' => 'Surf n Turf.png',
            ],
            [
                'menu_name' => 'Seafood Mixed Grill',
                'menu_price' => '120',
                'menu_type' => 'Grill',
                'menu_category' => 'Grills',
                'menu_desc' => 'Oysters, ribs, tiger prawns, triple cooked chips, lemons. Grilled oysters, ribs, tiger prawns, triple-cooked chips, and lemons for a flavorful and satisfying seafood medley.',
                'menu_image' => 'Seafood Mixed Grill.png',
            ],
            [
                'menu_name' => 'Rump Steak',
                'menu_price' => '40',
                'menu_type' => 'Grill',
                'menu_category' => 'Grills',
                'menu_desc' => 'Herbs, spices, with sauce Diane. A delicious steak seasoned with herbs and spices, served with the classic creamy Sauce Diane for a satisfying meal.',
                'menu_image' => 'Rump Steak.png',
            ],
            // Desserts
            [
                'menu_name' => 'Apple Cheesecake',
                'menu_price' => '13',
                'menu_type' => 'Grill',
                'menu_category' => 'Desserts',
                'menu_desc' => 'Lemon, Thyme. A delightful fusion of sweet apple cheesecake with a zesty lemon twist and a hint of aromatic thyme.',
                'menu_image' => 'Apple Cheesecake.png',
            ],
            [
                'menu_name' => 'Tiramisu',
                'menu_price' => '13',
                'menu_type' => 'Grill',
                'menu_category' => 'Desserts',
                'menu_desc' => 'Coffee, mascarpone, cocoa. A classic Italian dessert featuring layers of coffee-soaked ladyfingers, creamy mascarpone, and a dusting of cocoa powder, creating a rich and indulgent treat.',
                'menu_image' => 'Tiramisu.png',
            ],
            [
                'menu_name' => 'Chocolate Fondant',
                'menu_price' => '13',
                'menu_type' => 'Grill',
                'menu_category' => 'Desserts',
                'menu_desc' => 'Chocolate, oozing with caramel, served with vanilla ice cream. A decadent chocolate fondant with a luscious caramel center, paired with creamy vanilla ice cream for the ultimate dessert experience.',
                'menu_image' => 'Chocolate Fondant.png',
            ],
            [
                'menu_name' => 'Cheeseboard',
                'menu_price' => '16',
                'menu_type' => 'Grill',
                'menu_category' => 'Desserts',
                'menu_desc' => 'Selection of English and French cheeses, accompanied by chutney and crackers for a delightful cheese tasting experience.',
                'menu_image' => 'Cheeseboard.png',
            ],
            // Wine List
            // White Wines
            [
                'menu_name' => 'Chardonnay - Domaine Laroche, Chablis Premier Cru "Les Vaudevey"',
                'menu_price' => '65',
                'menu_type' => 'Wine',
                'menu_category' => 'White Wines',
                'menu_desc' => 'A premier cru Chablis featuring rich citrus, mineral, and floral notes, offering a complex and elegant white wine experience.',
                'menu_image' => 'Chardonnay Les Vaudevey.png',
            ],
            [
                'menu_name' => 'Sauvignon Blanc - Cloudy Bay, Marlborough, New Zealand',
                'menu_price' => '50',
                'menu_type' => 'Wine',
                'menu_category' => 'White Wines',
                'menu_desc' => 'A renowned New Zealand Sauvignon Blanc known for its vibrant tropical fruit aromas and crisp acidity, delivering a refreshing and zesty white wine experience.',
                'menu_image' => 'Sauvignon Blanc Cloudy Bay.png',
            ],
            [
                'menu_name' => 'Riesling - Dr. Loosen, Mosel, Germany',
                'menu_price' => '40',
                'menu_type' => 'Wine',
                'menu_category' => 'White Wines',
                'menu_desc' => 'An elegant German Riesling featuring floral and citrus notes, balanced by a touch of sweetness, creating a harmonious and aromatic white wine experience.',
                'menu_image' => 'Riesling Dr Loosen.png',
            ],
            [
                'menu_name' => 'Pinot Grigio - Jermann, Venezia Giulia, Italy',
                'menu_price' => '45',
                'menu_type' => 'Wine',
                'menu_category' => 'White Wines',
                'menu_desc' => 'A high-quality Italian Pinot Grigio offering crisp pear and apple notes, along with a subtle hint of almonds, providing a delightful and versatile white wine experience.',
                'menu_image' => 'Pinot Grigio Jermann.png',
            ],
            // Red Wines
            [
                'menu_name' => 'Cabernet Sauvignon - Silver Oak, Alexander Valley, USA',
                'menu_price' => '120',
                'menu_type' => 'Wine',
                'menu_category' => 'Red Wines',
                'menu_desc' => 'A premium Cabernet Sauvignon from California\'s Alexander Valley, known for its robust black fruit flavors, smooth tannins, and elegant structure, delivering a luxurious red wine experience.',
                'menu_image' => 'Cabernet Sauvignon Silver Oak.png',
            ],
            [
                'menu_name' => 'Merlot - Château Pétrus, Pomerol, France',
                'menu_price' => '700',
                'menu_type' => 'Wine',
                'menu_category' => 'Red Wines',
                'menu_desc' => 'An exceptional Pomerol Merlot from the renowned Château Pétrus, offering rich plum, black cherry, and truffle notes, along with a velvety texture, providing a truly luxurious and indulgent red wine experience.',
                'menu_image' => 'Merlot Chateau Petrus.png',
            ],
            [
                'menu_name' => 'Pinot Noir - Domaine de la Romanée-Conti, Romanée-Saint-Vivant Grand Cru, France',
                'menu_price' => '1800',
                'menu_type' => 'Wine',
                'menu_category' => 'Red Wines',
                'menu_desc' => 'An extraordinary Pinot Noir from the iconic Domaine de la Romanée-Conti, showcasing complex aromas of red berries, violets, and spices, along with a silky and refined palate, offering a truly exceptional and rare red wine experience.',
                'menu_image' => 'Pinot Noir Romanee Saint Vivant.png',
            ],
            [
                'menu_name' => 'Syrah/Shiraz - Penfolds Grange, South Australia, Australia',
                'menu_price' => '900',
                'menu_type' => 'Wine',
                'menu_category' => 'Red Wines',
                'menu_desc' => 'An iconic Australian Shiraz from Penfolds, Grange offers intense black fruit, spice, and cedar notes, along with a rich and opulent palate, providing a luxurious and bold red wine experience.',
                'menu_image' => 'Syrah Penfolds Grange.png',
            ],
            // Rosé Wines
            [
                'menu_name' => 'Rosé - Château d\'Esclans, Garrus, Côtes de Provence, France',
                'menu_price' => '160',
                'menu_type' => 'Wine',
                'menu_category' => 'Rosé Wines',
                'menu_desc' => 'A premium rosé wine from Château d\'Esclans, Garrus offers delicate strawberry and floral aromas, along with a crisp and refreshing palate, delivering a luxurious rosé wine experience.',
                'menu_image' => 'Rose Chateau d Esclans Garrus.png',
            ],
            [
                'menu_name' => 'Rosé - Domaines Ott, Château de Selle, Côtes de Provence, France',
                'menu_price' => '70',
                'menu_type' => 'Wine',
                'menu_category' => 'Rosé Wines',
                'menu_desc' => 'A classic rosé from Domaines Ott, Château de Selle offers elegant peach and citrus notes, balanced by a refreshing acidity, providing a delightful and sophisticated rosé wine experience.',
                'menu_image' => 'Rose Domaines Ott Chateau de Selle.png',
            ],
            [
                'menu_name' => 'Rosé - Whispering Angel, Côtes de Provence, France',
                'menu_price' => '35',
                'menu_type' => 'Wine',
                'menu_category' => 'Rosé Wines',
                'menu_desc' => 'A popular Côtes de Provence rosé, Whispering Angel features bright red fruit aromas, a crisp and dry palate, and a hint of minerality, delivering a refreshing and approachable rosé wine experience.',
                'menu_image' => 'Rose Whispering Angel.png',
            ],
            [
                'menu_name' => 'Rosé - Miraval, Côtes de Provence, France',
                'menu_price' => '45',
                'menu_type' => 'Wine',
                'menu_category' => 'Rosé Wines',
                'menu_desc' => 'A rosé wine from Château Miraval, owned by Brad Pitt and Angelina Jolie, offering delicate floral and berry aromas, a vibrant acidity, and a clean finish, providing a delightful and elegant rosé wine experience.',
                'menu_image' => 'Rose Miraval.png',
            ],
            // Champagne & Sparkling Wines
            [
                'menu_name' => 'Champagne - Dom Pérignon Vintage, France',
                'menu_price' => '250',
                'menu_type' => 'Wine',
                'menu_category' => 'Champagne & Sparkling Wines',
                'menu_desc' => 'A prestigious vintage Champagne from Dom Pérignon, offering rich toasty notes, vibrant citrus aromas, and a creamy texture, providing a luxurious and celebratory Champagne experience.',
                'menu_image' => 'Champagne Dom Perignon.png',
            ],
            [
                'menu_name' => 'Champagne - Krug Grande Cuvée, France',
                'menu_price' => '280',
                'menu_type' => 'Wine',
                'menu_category' => 'Champagne & Sparkling Wines',
                'menu_desc' => 'An exceptional Champagne from Krug, Grande Cuvée showcases a harmonious blend of diverse flavors, including ripe fruit, nuts, spices, and a subtle hint of honey, offering a truly indulgent and complex Champagne experience.',
                'menu_image' => 'Champagne Krug Grande Cuvee.png',
            ],
            [
                'menu_name' => 'Prosecco - Nino Franco Rustico, Italy',
                'menu_price' => '30',
                'menu_type' => 'Wine',
                'menu_category' => 'Champagne & Sparkling Wines',
                'menu_desc' => 'A high-quality Prosecco from Nino Franco, Rustico features lively apple and pear notes, along with a crisp and refreshing effervescence, delivering a delightful and approachable sparkling wine experience.',
                'menu_image' => 'Prosecco Nino Franco Rustico.png',
            ],
            [
                'menu_name' => 'Rosé Champagne - Billecart-Salmon Brut Rosé, France',
                'menu_price' => '90',
                'menu_type' => 'Wine',
                'menu_category' => 'Champagne & Sparkling Wines',
                'menu_desc' => 'A prestigious rosé Champagne from Billecart-Salmon, Brut Rosé offers elegant red fruit aromas, a fine mousse, and a delicate balance of sweetness and acidity, providing a luxurious and refined rosé Champagne experience.',
                'menu_image' => 'Rose Champagne Billecart Salmon Brut Rose.png',
            ],
            // Cocktails
            [
                'menu_name' => 'Classic Martini',
                'menu_price' => '12',
                'menu_type' => 'Wine',
                'menu_category' => 'Cocktails',
                'menu_desc' => 'Gin, Dry Vermouth, Olive or Lemon Twist. A timeless cocktail featuring gin and dry vermouth, stirred or shaken to perfection, and garnished with an olive or lemon twist, offering a sophisticated and iconic cocktail experience.',
                'menu_image' => 'Classic Martini.png',
            ],
            [
                'menu_name' => 'Margarita',
                'menu_price' => '10',
                'menu_type' => 'Wine',
                'menu_category' => 'Cocktails',
                'menu_desc' => 'Tequila, Triple Sec, Lime Juice. A classic cocktail featuring tequila, triple sec, and lime juice, served in a salt-rimmed glass, delivering a refreshing and tangy cocktail experience.',
                'menu_image' => 'Margarita.png',
            ],
            [
                'menu_name' => 'Old Fashioned',
                'menu_price' => '14',
                'menu_type' => 'Wine',
                'menu_category' => 'Cocktails',
                'menu_desc' => 'Bourbon, Sugar, Angostura Bitters, Water, Orange Twist. A timeless cocktail showcasing bourbon, sugar, bitters, and water, garnished with an orange twist, providing a rich and aromatic cocktail experience.',
                'menu_image' => 'Old Fashioned.png',
            ],
            [
                'menu_name' => 'Negroni',
                'menu_price' => '13',
                'menu_type' => 'Wine',
                'menu_category' => 'Cocktails',
                'menu_desc' => 'Gin, Campari, Sweet Vermouth, Orange Slice. A classic cocktail featuring gin, Campari, and sweet vermouth, garnished with an orange slice, offering a balanced and bittersweet cocktail experience.',
                'menu_image' => 'Negroni.png',
            ],
        ]);
        
    }
}
